apiVersion: v1
kind: Secret
metadata:
  name: {{ include "servellm.fullname" . }}-secrets
  labels:
    {{- include "servellm.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVELLM_API_KEYS: {{ .Values.secrets.apiKeys | quote }}
  SERVELLM_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
