apiVersion: v1
kind: Service
metadata:
  name: {{ include "servellm.fullname" . }}
  labels:
    {{- include "servellm.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "servellm.selectorLabels" . | nindent 4 }}
